"""Distributed auction task-allocation primitives for Agent 11."""

from .models import (
    AbstentionReason,
    AuctionState,
    AuctionStatus,
    Bid,
    BidAbstention,
    CapabilityProfile,
    FailureClass,
    RegisteredCapability,
    TaskAnnouncement,
    TaskAward,
    TaskFailure,
    WorkProduct,
)
from .runtime import (
    DeterministicMissionRuntime,
    MissionEvent,
    MissionEventType,
    MissionMetrics,
    MissionResult,
    TaskMetrics,
    TaskRunResult,
    TaskRunStatus,
)
from .scenario import TaskBlueprint
from .baseline import (
    AllocationComparison,
    CentralEvent,
    CentralEventType,
    CentralMissionMetrics,
    CentralMissionResult,
    CentralTaskMetrics,
    CentralTaskResult,
    CentralizedAllocationBaseline,
    compare_allocation_models,
)
from .evaluation import (
    CapabilityStressOverride,
    PeerStressOverride,
    ScenarioEvaluation,
    StressEvaluationReport,
    StressScenario,
    StressSuiteMetrics,
    TaskStressOverride,
    default_stress_scenarios,
    run_stress_evaluation,
)
from .llm import (
    HF_DEFAULT_BASE_URL,
    EvidenceRecord,
    HuggingFaceChatClient,
    JsonChatModel,
    ModelConfigurationError,
    ModelWorkDraft,
    StructuredModelError,
    build_llm_handlers,
    make_llm_task_handler,
)
from .hf_runtime import (
    HuggingFaceStructuredChatClient,
    ModelInvocationError,
)
from .demo import (
    ArchitectureRow,
    AuctionRow,
    DemoMode,
    DemoSnapshot,
    EventRow,
    StressRow,
    WorkProductRow,
    llm_runtime_status,
    run_demo,
    safe_run_demo,
)

__version__ = "0.1.0"

__all__ = [
    "AbstentionReason",
    "AllocationComparison",
    "ArchitectureRow",
    "AuctionRow",
    "AuctionState",
    "AuctionStatus",
    "Bid",
    "BidAbstention",
    "CapabilityProfile",
    "CapabilityStressOverride",
    "CentralEvent",
    "CentralEventType",
    "CentralMissionMetrics",
    "CentralMissionResult",
    "CentralTaskMetrics",
    "CentralTaskResult",
    "CentralizedAllocationBaseline",
    "DemoMode",
    "DemoSnapshot",
    "DeterministicMissionRuntime",
    "EvidenceRecord",
    "EventRow",
    "FailureClass",
    "HF_DEFAULT_BASE_URL",
    "HuggingFaceChatClient",
    "HuggingFaceStructuredChatClient",
    "JsonChatModel",
    "MissionEvent",
    "MissionEventType",
    "MissionMetrics",
    "MissionResult",
    "ModelConfigurationError",
    "ModelInvocationError",
    "ModelWorkDraft",
    "PeerStressOverride",
    "RegisteredCapability",
    "ScenarioEvaluation",
    "StressEvaluationReport",
    "StressRow",
    "StressScenario",
    "StressSuiteMetrics",
    "StructuredModelError",
    "TaskAnnouncement",
    "TaskAward",
    "TaskBlueprint",
    "TaskFailure",
    "TaskMetrics",
    "TaskRunResult",
    "TaskRunStatus",
    "TaskStressOverride",
    "WorkProduct",
    "WorkProductRow",
    "build_llm_handlers",
    "compare_allocation_models",
    "default_stress_scenarios",
    "llm_runtime_status",
    "make_llm_task_handler",
    "run_demo",
    "run_stress_evaluation",
    "safe_run_demo",
    "__version__",
]
